import Head from "next/head";
import Navbar from "@/components/Navbar/Navbar";
import Hero from "@/components/Hero/Hero";
import Specs from "@/components/Specs/Specs";
import { MainContainer } from "@/styles/global.styled";
import Video from "@/components/Video/Video";
import Usage from "@/components/Usage/Usage";
import Form from "@/components/Form/Form";
import Footer from "@/components/Footer/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Microfire</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <MainContainer>
        <Hero/>
        <Specs/>
        <Usage/>
        <Video/>
        <Form/>
        <Footer/>
      </MainContainer>
    </>
  );
}
