import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Image from "next/image";
import logo from "../assets/logo.png";
import heroImage from "../assets/mainpage.png"

export default function Home() {
  return (
    <>
      <Head>
        <title>Microfire</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header className={styles.navbarContainer}>
          <Image width={110} src={logo} alt="logo" />
          <button className={styles.navbarButton}>Contact</button>
        </header>
        <div className={styles.heroContent}>
          <section className={styles.leftContainer}>
            <h1>
              Yangın çıkmasını beklemeyin MicroFire Sticker ile hemen önleminizi
              alın
            </h1>
            <p>Otomatik Yangın Söndürücü MicroFire; alevi algıladığında hemen aktive olarak yangını söndürür. Küçük boyutuna göre büyük iş başarır. Çevreye ve ekipmana zarar vermez.</p>
            <button className={styles.heroButton}>Get In Touch</button>
          </section>
          <section className={styles.rightContainer}>
          <Image height={450} src={heroImage} alt="heroImage"/>
          </section>
        </div>
      </main>
    </>
  );
}
